package br.com.alura.financas.model;

public enum Pais {

	AFEGANISTAO, AFRICA_DO_SUL, ALBANIA, ALEMANHA, ANDORRA, ANGOLA, ANTIGA_E_BARBUDA, ARABIA_SAUDITA, ARGELIA,
	ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIJAO, BAHAMAS, BANGLADEXE, BARBADOS, BAREM, BELGICA, BELIZE, BENIM,
	BIELORRUSSIA, BOLIVIA, BOSNIA_E_HERZEGOVINA, BOTSUANA, BRASIL, BRUNEI, BULGARIA, BURQUINA_FASO, BURUNDI, BUTAO,
	CABO_VERDE, CAMARÕES, CAMBOJA, CANADA, CATAR, CAZAQUISTAO, CHADE, CHILE, CHINA, CHIPRE, COLOMBIA, COMORES,
	CONGO_BRAZZAVILLE, COREIA_DO_NORTE, COREIA_DO_SUL, COSOVO, COSTA_DO_MARFIM, COSTA_RICA, CROACIA, CUAITE, CUBA,
	DINAMARCA, DOMINICA, EGITO, EMIRADOS_ARABES_UNIDOS, EQUADOR, ERITREIA, ESLOVAQUIA, ESLOVENIA, ESPANHA,
	ESTADO_DA_PALESTINA, ESTADOS_UNIDOS, ESTONIA, ETIOPIA, FIJI, FILIPINAS, FINLANDIA, FRANCA, GABAO, GAMBIA, GANA,
	GEORGIA, GRANADA, GRECIA, GUATEMALA, GUIANA, GUINE, GUINE_EQUATORIAL, GUINE_BISSAU, HAITI, HONDURAS, HUNGRIA, IEMEN,
	ILHAS_MARECHAL, INDIA, INDONESIA, IRAO, IRAQUE, IRLANDA, ISLANDIA, ISRAEL, ITALIA, JAMAICA, JAPAO, JIBUTI, JORDANIA,
	LAUS, LESOTO, LETONIA, LIBANO, LIBERIA, LIBIA, LISTENSTAINE, LITUANIA, LUXEMBURGO, MACEDONIA, MADAGASCAR, MALASIA,
	MALAUI, MALDIVAS, MALI, MALTA, MARROCOS, MAURICIA, MAURITANIA, MEXICO, MIANMAR, MICRONESIA, MOCAMBIQUE, MOLDAVIA,
	MONACO, MONGOLIA, MONTENEGRO, NAMIBIA, NAURU, NEPAL, NICARAGUA, NIGER, NIGERIA, NORUEGA, NOVA_ZELANDIA, OMA,
	PAISES_BAIXOS, PALAU, PANAMA, PAPUA_NOVA_GUINE, PAQUISTAO, PARAGUAI, PERU, POLONIA, PORTUGAL, QUENIA, QUIRGUISTAO,
	QUIRIBATI, REINO_UNIDO, REPUBLICA_CENTRO_AFRICANA, REPUBLICA_CHECA, REPUBLICA_DEMOCRATICA_DO_CONGO,
	REPUBLICA_DOMINICANA, ROMENIA, RUANDA, RUSSIA, SALOMAO, SALVADOR, SAMOA, SANTA_LUCIA, SAO_CRISTOVAO_E_NEVES,
	SAO_MARINHO, SAO_TOME_E_PRINCIPE, SAO_VICENTE_E_GRANADINAS, SEICHELES, SENEGAL, SERRA_LEOA, SERVIA, SINGAPURA,
	SIRIA, SOMALIA, SRI_LANCA, SUAZILANDIA, SUDAO, SUDAO_DO_SUL, SUECIA, SUICA, SURINAME, TAILANDIA, TAIUA, TAJIQUISTAO,
	TANZANIA, TIMOR_LESTE, TOGO, TONGA, TRINDADE_E_TOBAGO, TUNISIA, TURCOMENISTAO, TURQUIA, TUVALU, UCRANIA, UGANDA,
	URUGUAI, USBEQUISTAO, VANUATU, VATICANO, VENEZUELA, VIETNAME, ZAMBIA, ZIMBABUE;
}
